#!/usr/bin/env bash
# same as task 0 but -f added to ln to forcefully remove the file if it exists

sudo sed -i "s/8080/80/" /etc/nginx/sites-enabled/default
sudo service nginx restart
echo "" | sudo dd status=none of=/run/nginx.pid
