#!/usr/bin/env bash
# This script is displaying "Best School" 10 times

passwd_file="/etc/passwd"

while IFS=: read -r username _ userid groupid info home shell; do
    password_field=$(echo "$info" | cut -d ',' -f 2)

    user_info=$(echo "$info" | cut -d ',' -f 3)

    echo "The user $username is part of the group $groupid gang,"\
    "lives in $home and rides $shell."\
    "$userid's place is protected by the passcode $password_field,"\
    "more info about the user here: $user_info"
done < "$passwd_file"
